### ISSUE TITLE
Rewrite user agent (URL fetching) code to Python

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#178]
Issue to track rewriting user agent (`LWP::UserAgent`) to Python.

It goes without saying that Media Cloud relies heavily on fetching stuff from the web. Currently we use [`LWP::UserAgent`](http://search.cpan.org/perldoc/LWP::UserAgent) to do the job, but we want to move to using Python's [`requests`](http://docs.python-requests.org/en/master/) so that the new code which wants to fetch some stuff from web as well could be written directly in Python.

Feature branch is [`web_useragent_python`](https://github.com/berkmancenter/mediacloud/tree/web_useragent_python).

**Tasks:**

- [x] Wrap usages of `LWP::UserAgent` into `MediaWords::Util::Web::UserAgent` to establish the user agent's API that we're using
- [x] Rename `HTTP::HashServer` to `MediaWords::Test::HTTP::HashServer`
- [x] Rewrite `MediaWords::Test::HTTP::HashServer` to Python to make it easier to test user agent code against a test web server
- [x] Make `parallel_get()` into a method of the `MediaWords::Util::Web::UserAgent`
- [x] Move [alarabiya hack](https://github.com/berkmancenter/mediacloud/blob/master/lib/MediaWords/Crawler/Download/DefaultFetcher.pm#L30-L55) to `MediaWords::Util::Web::UserAgent` as all the requests would probably like to employ this hack
- [x] Cover `MediaWords::Util::Web::UserAgent` with Perl unit tests to help retain the same expected behavior after the Python rewrite:
    * [x] max. download size
    * [x] max. redirects
    * [x] `User-Agent:` header
    * [x] `From:` header
    * [x] UTF-8 response
    * [x] non-UTF-8 response
    * [x] invalid encoding
    * [x] timeouts
    * [x] retries via `::Determined` of specific HTTP status codes
    * [x] retry timing via `::Determined`, plus custom timing
    * [x] max. redirects
    * [x] whether or not cookies are being stored between redirects
    * [x] blacklisted URLs
    * [x] HTTP request log in `data/logs/`
    * [x] `GET`
    * [x] `POST`
    * [x] `request()`: custom `METHOD`
    * [x] `request()`: custom headers
    * [x] `request()`: custom content type
    * [x] `request()`: custom content (`POST` data) -- both hashref and string
    * [x] `request()`: authorization
    * [x] response: HTTP status code, message, status line
    * [x] response: HTTP headers
    * [x] response: content type
    * [x] response: decoded content (UTF-8, non-UTF-8, and invalid UTF-8)
    * [x] response: successful and unsuccessful responses
    * [x] response: redirects and previous
    * [x] response: get original request
    * [x] response: errors on client/server side
    * [x] `get_string()`
- [x] Make `get()` and `post()` use `request()` internally; run `fix_common_url_mistakes()`, `is_http_url()`, add HTTP auth every time
- [x] Rewrite `MediaWords::Util::Web::UserAgent` and its tests to Python
- [x] Add test for GB2312 (#185)

**Comment by pypt** [comment]
Covered existing LWP::UserAgent-based implementation with unit tests in https://github.com/berkmancenter/mediacloud/tree/web_useragent_python, time to rewrite it to Python now.

**Comment by pypt** [comment]
Oh, I rewrote [`HashServer` to Python too](https://github.com/berkmancenter/mediacloud/blob/master/mediacloud/mediawords/test/http/hash_server.py), so now we can test fetching stuff from the web using both Perl and Python.

The rewritten version is more advanced in that it creates forks for every request, so one can test stuff such as `parallel_get()`, timeouts, crashes etc.

**Comment by pypt** [comment]
Deployed. There might be some small, easily fixable bugs left here and there (e.g. related to UTF-8 encoding), but in general everything seems to work (e.g. see [Japanese query for "North Korea" in Dashboard](https://dashboard.mediacloud.org/#query/["北朝鮮"]/[{}]/["2017-10-26"]/["2017-11-9"]/[{"uid":2,"name":"北朝鮮","color":"20b1b8"}])).

Fixes #185.
